<a href="https://colab.research.google.com/github/veronicabaron224/Linear-Algebra-58019/blob/main/Linear_Transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**To find the inverse of a matrix, the matrix is passed to the linalg.inv() of the NumPy module:**

In [6]:
import numpy as np

A = np.array([[4,3],[-5,9]]) #Creation of matrix A
print(A)
inv_A = np.linalg.inv(A)
print(inv_A)

[[ 4  3]
 [-5  9]]
[[ 0.17647059 -0.05882353]
 [ 0.09803922  0.07843137]]


In [7]:
B = np.array([[20],[26]])
print(B)

[[20]
 [26]]


In [9]:
X = np.linalg.inv(A).dot(B) #Multiplying the inverse of A to the dot product of B
print(X)

[[2.]
 [4.]]


In [10]:
X = np.dot(inv_A, B) #Dot product of the given variables
print(X)

[[2.]
 [4.]]


**Exercise: Solving of a system of three linear equations**

In [11]:
A = np.array([[4,3,2],[-2,2,3],[3,-5,2]])
B = np.array([[25],[-10],[-4]])
X = np.linalg.inv(A).dot(B)
print(X)

[[ 5.]
 [ 3.]
 [-2.]]


**Application: Word Problem**

In [13]:
A = np.array([[20,10],[17,22]])
print(A)
inv_A = np.linalg.inv(A)
print(inv_A)

[[20 10]
 [17 22]]
[[ 0.08148148 -0.03703704]
 [-0.06296296  0.07407407]]


In [14]:
B = np.array([[350],[500]])
print(B)

[[350]
 [500]]


In [16]:
X = np.dot(inv_A,B)
print(X)

[[10.]
 [15.]]
