<a href="https://colab.research.google.com/github/veronicabaron224/Linear-Algebra-58019/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Problem 1**

1. AB
2. D + D
3. 2C

In [11]:
import numpy as np

#Given Matrices
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = np.array([[1,2],[3,4]])

In [29]:
#AB
prob1 = np.dot(A,B)
print(prob1)

[[22 28]
 [49 64]]


In [15]:
#D+D
prob2 = D + D
print(prob2)

[[2 4]
 [6 8]]


In [17]:
#2C
prob3 = 2*C
print(prob3)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


**Problem 2**

Given the linear combination below, try to create a corresponding matrix representing it and display its type, shape, and its dimension.

$$\theta = 5x + 3y - z$$

In [50]:
#Given matrix
matrix = np.array([5,3,-1])
print(matrix) #With only one row and a number of columns (i.e., 3 columns), this is a row matrix

[ 5  3 -1]


In [51]:
#Print type
print(type(matrix))

<class 'numpy.ndarray'>


In [52]:
#Print data type
matrix.dtype

dtype('int64')

In [53]:
#Print size
matrix.size

3

In [54]:
#Print shape
matrix.shape

(3,)

In [55]:
#Print dimension
matrix.ndim

1