<a href="https://colab.research.google.com/github/veronicabaron224/Linear-Algebra-58019/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np #Importing of NumPy. This code was ran first to make numpy usable in all other code cells.

**Question 1.** (20 points) Create a 4 x 4 matrix whose diagonal elements are all one (1's). Name it as matrix "C". Show your solutions using Python codes and do not forget to label them on the Text Cell.

In [2]:
C = np.identity(4) #Use of the identity matrix, which fills the main diagonal with 1.
print(C) #Printing of matrix "C"

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Question 2.** (20 points) In relation to Question 1, show a solution that doubles all the values of each element. Show your solutions using Python codes and do not forget to label them on the Text Cell.

In [3]:
double = 2*C #Doubles the values of matrix "C"
print(double) #Prints doubled matrix "C"

[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


**Question 3.** (10 points) Find the cross-product of matrices, A = [2,7,4] and B = [3,9,8]. Show your solutions using Python codes and do not forget to label them on the Text Cell.

In [4]:
A = [2,7,4] #Matrix A
B = [3,9,8] #Matrix B

cross = np.cross(A,B) #Calculates the cross product of matrix A and B
print(cross)

[20 -4 -3]
