<a href="https://colab.research.google.com/github/veronicabaron224/Linear-Algebra-58019/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Matrix and its Operations**

Create a NumPy program that performs the operations of the given matrices:

    sum = A + B
    difference1 = B - A
    difference2 = A - B

In [5]:
import numpy as np

#Given
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])

[[ 1 -3]
 [ 6  4]]
[[11 -3]
 [-2  2]]
[[-11   3]
 [  2  -2]]


In [8]:
#Sum
print(A+B)

[[ 1 -3]
 [ 6  4]]


In [9]:
#Difference 1
print(B-A)

[[11 -3]
 [-2  2]]


In [10]:
#Difference 2
print(A-B)

[[-11   3]
 [  2  -2]]
