<a href="https://colab.research.google.com/github/veronicabaron224/Linear-Algebra-58019/blob/main/Vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Matrix Algebra**

Numpy is a library that can allow you to create multi-dimensional arrays. It stands for *numerical python*

In [ ]:
#numpy
import numpy as np

a = np.array([1,2,3]) #This is an example of 1x3 matrix
print(a)

[1 2 3]


In [ ]:
import numpy as np

b = np.array([[1,2,3],[4,5,6]]) #This is an example of 2x3 matrix; it is a rectangular matrix 
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

c = np.array([[1,2,3],[4,5,6],[7,8,9]]) #This is an example of 3x3 matrix; it is a square matrix
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np

d = np.full((3,3),7) #In which you input the size first and then the fill value
print(d)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
import numpy as np

e = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(e)
e = np.diagonal([[1,2,3],[4,5,6],[7,8,9]]) #This will only take the values of the diagonal
print(e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [ ]:
import numpy as np

f = np.eye(3) #This is an identity matrix. Identity matrices are always square
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np

g = np.zeros((3,3)) #This is a zero matrix where all elements are zero
print(g)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np

h = np.empty((0,12)) #This creates an empty matrix; no elements
print(h)

[]


In [ ]:
import numpy as np

i = np.full((3,3),7) #Addition
print(i+i)

[[14 14 14]
 [14 14 14]
 [14 14 14]]


In [ ]:
import numpy as np

j = np.full((3,3),7) #Subtraction
print(j-j)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
